# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rzv/source/OOP/POO_Lab10

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rzv/source/OOP/POO_Lab10

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rzv/source/OOP/POO_Lab10/CMakeFiles /Users/rzv/source/OOP/POO_Lab10//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rzv/source/OOP/POO_Lab10/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rzv/source/OOP/POO_Lab10/CMakeFiles /Users/rzv/source/OOP/POO_Lab10//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rzv/source/OOP/POO_Lab10/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named app_autogen_timestamp_deps

# Build rule for target.
app_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_autogen_timestamp_deps
.PHONY : app_autogen_timestamp_deps

# fast build rule for target.
app_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_autogen_timestamp_deps.dir/build.make CMakeFiles/app_autogen_timestamp_deps.dir/build
.PHONY : app_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named app_autogen

# Build rule for target.
app_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_autogen
.PHONY : app_autogen

# fast build rule for target.
app_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_autogen.dir/build.make CMakeFiles/app_autogen.dir/build
.PHONY : app_autogen/fast

app_autogen/mocs_compilation.o: app_autogen/mocs_compilation.cpp.o
.PHONY : app_autogen/mocs_compilation.o

# target to build an object file
app_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app_autogen/mocs_compilation.cpp.o
.PHONY : app_autogen/mocs_compilation.cpp.o

app_autogen/mocs_compilation.i: app_autogen/mocs_compilation.cpp.i
.PHONY : app_autogen/mocs_compilation.i

# target to preprocess a source file
app_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app_autogen/mocs_compilation.cpp.i
.PHONY : app_autogen/mocs_compilation.cpp.i

app_autogen/mocs_compilation.s: app_autogen/mocs_compilation.cpp.s
.PHONY : app_autogen/mocs_compilation.s

# target to generate assembly for a file
app_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app_autogen/mocs_compilation.cpp.s
.PHONY : app_autogen/mocs_compilation.cpp.s

domain.o: domain.cpp.o
.PHONY : domain.o

# target to build an object file
domain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/domain.cpp.o
.PHONY : domain.cpp.o

domain.i: domain.cpp.i
.PHONY : domain.i

# target to preprocess a source file
domain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/domain.cpp.i
.PHONY : domain.cpp.i

domain.s: domain.cpp.s
.PHONY : domain.s

# target to generate assembly for a file
domain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/domain.cpp.s
.PHONY : domain.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/main.cpp.s
.PHONY : main.cpp.s

rentalcart.o: rentalcart.cpp.o
.PHONY : rentalcart.o

# target to build an object file
rentalcart.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/rentalcart.cpp.o
.PHONY : rentalcart.cpp.o

rentalcart.i: rentalcart.cpp.i
.PHONY : rentalcart.i

# target to preprocess a source file
rentalcart.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/rentalcart.cpp.i
.PHONY : rentalcart.cpp.i

rentalcart.s: rentalcart.cpp.s
.PHONY : rentalcart.s

# target to generate assembly for a file
rentalcart.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/rentalcart.cpp.s
.PHONY : rentalcart.cpp.s

repo.o: repo.cpp.o
.PHONY : repo.o

# target to build an object file
repo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/repo.cpp.o
.PHONY : repo.cpp.o

repo.i: repo.cpp.i
.PHONY : repo.i

# target to preprocess a source file
repo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/repo.cpp.i
.PHONY : repo.cpp.i

repo.s: repo.cpp.s
.PHONY : repo.s

# target to generate assembly for a file
repo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/repo.cpp.s
.PHONY : repo.cpp.s

service.o: service.cpp.o
.PHONY : service.o

# target to build an object file
service.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/service.cpp.o
.PHONY : service.cpp.o

service.i: service.cpp.i
.PHONY : service.i

# target to preprocess a source file
service.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/service.cpp.i
.PHONY : service.cpp.i

service.s: service.cpp.s
.PHONY : service.s

# target to generate assembly for a file
service.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/service.cpp.s
.PHONY : service.cpp.s

tests.o: tests.cpp.o
.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i
.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s
.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app_autogen"
	@echo "... app_autogen_timestamp_deps"
	@echo "... app"
	@echo "... app_autogen/mocs_compilation.o"
	@echo "... app_autogen/mocs_compilation.i"
	@echo "... app_autogen/mocs_compilation.s"
	@echo "... domain.o"
	@echo "... domain.i"
	@echo "... domain.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... rentalcart.o"
	@echo "... rentalcart.i"
	@echo "... rentalcart.s"
	@echo "... repo.o"
	@echo "... repo.i"
	@echo "... repo.s"
	@echo "... service.o"
	@echo "... service.i"
	@echo "... service.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

